# company_symbols.py

company_to_symbol = {
    "Vodafone Idea Limited": "IDEA",
    "Yes Bank Limited": "YESBANK",
    "GTL Infrastructure Limited": "GTLINFRA",
    "Zomato Limited": "ZOMATO",
    "Punjab National Bank": "PNB",
    "RattanIndia Power Limited": "RTNPOWER",
    "Godha Cabcon & Insulation Limited": "GODHA",
    "Bharat Electronics Limited": "BEL",
    "Samvardhana Motherson International Limited": "MOTHERSON",
    "Alok Industries Limited": "ALOKINDS",
    "Indian Energy Exchange Limited": "IEX",
    "Indian Renewable Energy Development Agency Limited": "IREDA",
    "Indus Towers Limited": "INDUSTOWER",
    "HFCL Limited": "HFCL",
    "Jaiprakash Power Ventures Limited": "JPPOWER",
    "Hindustan Construction Company Limited": "HCC",
    "Tata Steel Limited": "TATASTEEL",
    "IDFC First Bank Limited": "IDFCFIRSTB",
    "Sakuma Exports Limited": "SAKUMA",
    "Indian Railway Finance Corporation Limited": "IRFC",
    "Steel Authority of India Limited": "SAIL",
    "Ujjivan Small Finance Bank Limited": "UJJIVANSFB",
    "Suzlon Energy Limited": "SUZLON",
    "L&T Finance Limited": "LTF",
    "NMDC Limited": "NMDC",
    "Dish TV India Limited": "DISHTV",
    "NTPC Limited": "NTPC",
    "Kamdhenu Ventures Limited": "KAMOPAINTS",
    "REC Limited": "RECLTD",
    "Indian Infotech and Software Limited": "INDINFO",
    "TruCap Finance Limited": "TRU",
    "Sawaca Business Machines Limited": "SAWABUSI",
    "MPS Infotecnics Limited": "VISESHINFO",
    "Religare Enterprises Limited": "RELIGARE",
    "NHPC Limited": "NHPC",
    "GMR Airports Infrastructure Limited": "GMRINFRA",
    "Canara Bank": "CANBK",
    "GAIL (India) Limited": "GAIL",
    "Castrol India Limited": "CASTROLIND",
    "Texmaco Rail & Engineering Limited": "TEXRAIL",
    "Indian Oil Corporation Limited": "IOC",
    "Bajaj Hindusthan Sugar Limited": "BAJAJHIND",
    "FCS Software Solutions Limited": "FCSSOFT",
    "Rashtriya Chemicals and Fertilizers Limited": "RCF",
    "Power Finance Corporation Limited": "PFC",
    "National Fertilizers Limited": "NFL",
    "Visagar Financial Services Limited": "VISAGAR",
    "IRB Infrastructure Developers Limited": "IRB",
    "Reliance Power Limited": "RPOWER",
    "Union Bank of India": "UNIONBANK",
    "Jio Financial Services Limited": "JIOFIN",
    "Vedanta Limited": "VEDL",
    "Wipro Limited": "WIPRO",
    "Shree Renuka Sugars Limited": "RENUKA",
    "Orient Cement Limited": "ORIENTCEM",
    "Tata Motors Limited": "TATAMOTORS",
    "UCO Bank": "UCOBANK",
    "IDFC Limited": "IDFC",
    "Vikas Lifecare Limited": "VIKASLIFE",
    "Equinox India Developments Limited": "IBREALEST",
    "Allied Digital Services Limited": "ADSL",
    "ITC Limited": "ITC",
    "G G Engineering Limited": "GGENG",
    "Alankit Limited": "ALANKIT",
    "Bharat Heavy Electricals Limited": "BHEL",
    "National Aluminium Company Limited": "NATIONALUM",
    "Infibeam Avenues Limited": "INFIBEAM",
    "NBCC (India) Limited": "NBCC",
    "Bank of Baroda Limited": "BANKBARODA",
    "Power Grid Corporation of India Limited": "POWERGRID",
    "Oil and Natural Gas Corporation Limited": "ONGC",
    "Trident Limited": "TRIDENT",
    "The South Indian Bank Limited": "SOUTHBANK",
    "PTC India Financial Services Limited": "PFS",
    "JSW Infrastructure Limited": "JSWINFRA",
    "Teamo Productions HQ Limited": "TPHQ",
    "BLS International Services Limited": "BLS",
    "Empower India Limited": "EMPOWER",
    "Bank of Maharashtra": "MAHABANK",
    "State Bank of India": "SBIN",
    "Ashok Leyland Limited": "ASHOKLEY",
    "The India Cements Limited": "INDIACEM",
    "HDFC Bank Limited": "HDFCBANK",
    "Emami Limited": "EMAMILTD",
    "IFCI Limited": "IFCI",
    "Vikas Ecotech Limited": "VIKASECO",
    "Rail Vikas Nigam Limited": "RVNL",
    "MPS Infotecnics Limited": "VISESHINFO",
    "Manappuram Finance Limited": "MANAPPURAM",
    "Ajooni Biotech Limited": "AJOONI",
    "Davangere Sugar Company Limited": "DAVANGERE",
    "Garden Reach Shipbuilders & Engineers Limited": "GRSE",
    "Housing and Urban Development Corporation Limited": "HUDCO",
    "Biocon Limited": "BIOCON",
    "Zee Entertainment Enterprises Limited": "ZEEL",
    "Jaiprakash Associates Limited": "JPASSOCIAT",
    "DiGiSPICE Technologies Limited": "DIGISPICE",
    "APPLE": "AAPL",
    "MICROSOFT": "MSFT",
    "GOOGLE": "GOOGL",
    "AMAZON": "AMZN",
    "TESLA": "TSLA",
    "FACEBOOK": "META",
    "BERKSHIRE HATHAWAY": "BRK-A",
    "JOHNSON & JOHNSON": "JNJ",
    "VISA": "V",
    "WALMART": "WMT",
    "JPMORGAN CHASE": "JPM",
    "MASTERCARD": "MA",
    "PROCTER & GAMBLE": "PG",
    "UNITEDHEALTH": "UNH",
    "NVIDIA": "NVDA",
    "HOME DEPOT": "HD",
    "PAYPAL": "PYPL",
    "WALT DISNEY": "DIS",
    "NETFLIX": "NFLX",
    "ADOBE": "ADBE",
    "PEPSICO": "PEP",
    "COCA-COLA": "KO",
    "INTEL": "INTC",
    "VERIZON": "VZ",
    "AT&T": "T",
    "CISCO": "CSCO",
    "SALESFORCE": "CRM",
    "NIKE": "NKE",
    "EXXON MOBIL": "XOM",
    "CHEVRON": "CVX",
    "PHILIP MORRIS": "PM",
    "PFIZER": "PFE",
    "ABBVIE": "ABBV",
    "MERCK": "MRK",
    "BROADCOM": "AVGO",
    "QUALCOMM": "QCOM",
    "IBM": "IBM",
    "ORACLE": "ORCL",
    "SAP": "SAP",
    "ZOOM": "ZM",
    "SHOPIFY": "SHOP",
    "TWITTER": "TWTR",
    "UBER": "UBER",
    "LYFT": "LYFT",
    "SQUARE": "SQ",
    "SNAPCHAT": "SNAP",
    "DROPBOX": "DBX",
    "SPOTIFY": "SPOT",
    "ROBINHOOD": "HOOD",
    "REDDIT": "REDDIT",
    "SNOWFLAKE": "SNOW",
    "AIRBNB": "ABNB",
    "DOORDASH": "DASH",
    "ZOOM": "ZM",
    "DOCUSIGN": "DOCU",
    "TESLA": "TSLA",
    "RIVIAN": "RIVN",
    "NIO": "NIO",
    "XPENG": "XPEV",
    "FORD": "F",
    "GENERAL MOTORS": "GM",
    "TOYOTA": "TM",
    "HONDA": "HMC",
    "NISSAN": "NSANY",
    "VOLKSWAGEN": "VWAGY",
    "BMW": "BMWYY",
    "DAIMLER": "DDAIF",
    "MERCEDES-BENZ": "DDAIF",
    "AUDI": "AUDVF",
    "FERRARI": "RACE",
    "LAMBORGHINI": "VLKAY",
    "BUGATTI": "PCARF",
    "MASERATI": "STLA",
    "BENTLEY": "VLKAY",
    "ROLLS-ROYCE": "RR",
    "ASTON MARTIN": "AML",
    "PORSCHE": "POAHY",
    "JAGUAR": "TTM",
    "LAND ROVER": "TTM",
    "SUBARU": "FUJHY",
    "MAZDA": "MZDAY",
    "MITSUBISHI": "MSBHY",
    "ISUZU": "ISUZY",
    "KIA": "KIMTF",
    "HYUNDAI": "HYMTF",
    "SAMSUNG": "SSNLF",
    "LG": "LPL",
    "SONY": "SONY",
    "PANASONIC": "PCRFY",
    "SHARP": "SHCAY",
    "PHILIPS": "PHG",
    "TOSHIBA": "TOSBF",
    "HITACHI": "HTHIY",
    "FUJIFILM": "FUJIY",
    "NIKON": "NINOY",
    "CANON": "CAJ",
    "OLYMPUS": "OCPNY",
    "PIONEER": "PNCOF",
    "ONKYO": "ONKYO",
    "JVC": "JVC",
    "KENWOOD": "KENWOOD",
    "PIONEER": "PNCOF",
    "YAMAHA": "YAMCY",
    "DENON": "DENON",
    "BOSE": "BOSE",
    "BANG & OLUFSEN": "BO",
    "SENNHEISER": "SENNHEISER",
    "PHILIPS": "PHG",
    "BOSCH": "ROBFY",
    "SIEMENS": "SIEGY",
    "GE": "GE",
    "HONEYWELL": "HON",
    "3M": "MMM",
    "ABB": "ABB",
    "SCHNEIDER ELECTRIC": "SBGSF",
    "EMERSON": "EMR",
    "ROCKWELL AUTOMATION": "ROK",
    "KEYENCE": "KEYCY",
    "YASKAWA": "YASKY",
    "MITSUBISHI ELECTRIC": "MIELY",
    "FUJI ELECTRIC": "FELTY",
    "HITACHI": "HTHIY",
    "TOSHIBA": "TOSBF",
    "PANASONIC": "PCRFY",
    "SONY": "SONY",
    "SAMSUNG": "SSNLF",
    "LG": "LPL",
    "VESTAS": "VWDRY",
    "SIEMENS GAMESA": "GCTAY",
    "GE RENEWABLE ENERGY": "GE",
    "NEXTERA ENERGY": "NEE",
    "DUKE ENERGY": "DUK",
    "DOMINION ENERGY": "D",
    "AMERICAN ELECTRIC POWER": "AEP",
    "SOUTHERN COMPANY": "SO",
    "EXELON": "EXC",
    "FIRSTENERGY": "FE",
    "PG&E": "PCG",
    "PPL": "PPL",
    "SCE&G": "SCEG",
    "NV ENERGY": "NVE",
    "TECO ENERGY": "TE",
    "CONSOLIDATED EDISON": "ED",
    "ENTERGY": "ETR",
    "EVERGY": "EVRG",
    "HAWAIIAN ELECTRIC": "HE",
    "IDACORP": "IDA",
    "ALLIANT ENERGY": "LNT",
    "XCEL ENERGY": "XEL",
    "PUBLIC SERVICE ENTERPRISE GROUP": "PEG",
    "FORTIS": "FTS",
    "HYDRO ONE": "H",
    "EMERA": "EMA",
    "ALTAGAS": "ALA",
    "TRANSCANADA": "TRP",
    "ENBRIDGE": "ENB",
    "PEMBINA": "PBA",
    "INTER PIPELINE": "IPL",
    "KEYERA": "KEY",
    "VERMILION ENERGY": "VET",
    "CRESCENT POINT ENERGY": "CPG",
    "WHITECAP RESOURCES": "WCP",
    "TORC OIL & GAS": "TOG",
    "OBSIDIAN ENERGY": "OBE",
    "PRAIRIESKY ROYALTY": "PSK",
    "FREEHOLD ROYALTIES": "FRU",
    "RAGING RIVER EXPLORATION": "RRX",
    "SPARTAN ENERGY": "SPE",
    "BAYTEX ENERGY": "BTE",
    "MEG ENERGY": "MEG",
    "SEVEN GENERATIONS ENERGY": "VII",
    "PENGROWTH ENERGY": "PGF",
    "PENN WEST PETROLEUM": "PWE",
    "ATHABASCA OIL": "ATH",
    "JUPITER RESOURCES": "JUPR",
    "NUVISTA ENERGY": "NVA",
    "CENOVUS ENERGY": "CVE",
    "CANADIAN NATURAL RESOURCES": "CNQ",
    "SUNCOR ENERGY": "SU",
    "HUSKY ENERGY": "HSE",
    "IMPERIAL OIL": "IMO",
    "NEXEN ENERGY": "NXY",
    "TALISMAN ENERGY": "TLM",
    "DEVON ENERGY": "DVN",
    "MURPHY OIL": "MUR",
    "APACHE CORPORATION": "APA",
    "MARATHON OIL": "MRO",
    "CONOCOPHILLIPS": "COP",
    "CHEVRON": "CVX",
    "EXXONMOBIL": "XOM",
    "BP": "BP",
    "ROYAL DUTCH SHELL": "RDS-A",
    "TOTAL": "TOT",
    "EQUINOR": "EQNR",
    "ENI": "E",
    "OMV": "OMVKY",
    "REPSOL": "REPYY",
    "GAZPROM": "OGZPY",
    "LUKOIL": "LUKOY",
    "ROSNEFT": "OJSCY",
    "PETROBRAS": "PBR",
    "CNOOC": "CEO",
    "PETROCHINA": "PTR",
    "SINOPEC": "SNP",
    "PETRONAS": "PETR",
    "CNPC": "CNPC",
    "KAZMUNAIGAS": "KMG",
    "SAUDI ARAMCO": "ARAMCO",
    "QATAR PETROLEUM": "QATPE",
    "ADNOC": "ADNOC",
    "KUWAIT OIL": "KOC",
    "BAHRAIN PETROLEUM": "BAPCO",
    "Kingkey Financial International (Holdings) Limited": "1468.HK",
    "Supply@ME Capital plc": "SYME.L",
    "Echo Energy plc": "ECHO.L",
    "Vodafone Idea Limited": "IDEA.NS",
    "United Energy Group Limited": "0467.HK",
    "LATAM Airlines Group S.A.": "LTM.SN",
    "China Grand Automotive Services Group Co.,Ltd": "600297.SS",
    "BAIC BluePark New Energy Technology Co.,Ltd.": "600733.SS",
    "Lingyi iTech (Guangdong) Company": "002600.SZ",
    "Hainan Airlines Holding Co., Ltd.": "600221.SS",
    "PT Barito Pacific Tbk": "BRPT.JK",
    "China Construction Bank Corporation": "0939.HK",
    "Bluejay Mining plc": "JAY.L",
    "PT GoTo Gojek Tokopedia Tbk": "GOTO.JK",
    "Topindo Solusi Komunika Tbk.": "TOSK.JK",
    "SAS AB (publ)": "SAS.ST",
    "Mosman Oil and Gas Limited": "MSMN.L",
    "Energy Absolute Public Company Limited": "EA.BK",
    "Energy Absolute Public Company Limited": "EA-R.BK",
    "SenseTime Group Inc.": "0020.HK",
    "Industrial and Commercial Bank of China Limited": "1398.HK",
    "PT Buana Lintas Lautan Tbk": "BULL.JK",
    "PT Totalindo Eka Persada Tbk": "TOPS.JK",
    "Guangdong Highsun Group Co.,Ltd.": "000861.SZ",
    "Agricultural Bank of China Limited": "601288.SS",
    "Inner Mongolia Baotou Steel Union Co., Ltd.": "600010.SS",
    "Meyer Burger Technology AG": "MBTN.SW",
    "China Vered Financial Holding Corporation Limited": "0245.HK",
    "PT Era Media Sejahtera Tbk": "DOOH.JK",
    "Industrial and Commercial Bank of China Limited": "601398.SS",
    "Sabuy Technology Public Company Limited": "SABUY.BK",
    "Sabuy Technology Public Company Limited": "SABUY-R.BK",
    "CAP-XX Limited": "CPX.L",
    "China Tower Corporation Limited": "0788.HK",
    "Helium One Global Ltd": "HE1.L",
    "Nippon Telegraph and Telephone Corporation": "9432.T",
    "Cybergun S.A.": "ALCYB.PA",
    "China Vanke Co., Ltd.": "000002.SZ",
    "Orient Group Incorporation": "600811.SS",
    "PT Bank Rakyat Indonesia (Persero) Tbk": "BBRI.JK",
    "PT Samudera Indonesia Tbk": "SMDR.JK",
    "Jinke Property Group Co., Ltd.": "000656.SZ",
    "East Money Information Co.,Ltd.": "300059.SZ",
    "Clontarf Energy plc": "CLON.L",
    "Gfinity plc": "GFIN.L",
    "Gemdale Corporation": "600383.SS",
    "Bank of China Limited": "3988.HK",
    "Beijing Hualian Department Store Co., Ltd": "000882.SZ",
    "Wintime Energy Group Co.,Ltd.": "600157.SS",
    "BOE Technology Group Company Limited": "000725.SZ",
    "5i5j Holding Group Co., Ltd.": "000560.SZ",
    "Chengtun Mining Group Co., Ltd.": "600711.SS",
    "Offcn Education Technology Co., Ltd.": "002607.SZ",
    "Gosuncn Technology Group Co., Ltd.": "300098.SZ",
    "Türkiye Is Bankasi A.S.": "ISCTR.IS",
    "Founder Technology Group Co.,Ltd.": "600601.SS",
    "PT Lippo Karawaci Tbk": "LPKR.JK",
    "PT Darma Henwa Tbk": "DEWA.JK",
    "Poly Developments and Holdings Group Co., Ltd.": "600048.SS",
    "RiseSun Real Estate Development Co.,Ltd": "002146.SZ",
    "Power Construction Corporation of China, Ltd": "601669.SS",
    "CGN Power Co., Ltd.": "003816.SZ",
    "Bank of China Limited": "601988.SS",
    "Nex Point Public Company Limited": "NEX.BK",
    "Nex Point Public Company Limited": "NEX-R.BK",
    "China Energy Engineering Corporation Limited": "601868.SS",
    "PetroChina Company Limited": "0857.HK",
    "Atlantis Subsea Indonesia Tbk.": "ATLA.JK",
    "PetroChina Company Limited": "601857.SS",
    "Trabzonspor Sportif Yatirim ve Futbol Isletmeciligi Ticaret A.S.": "TSPOR.IS",
    "China Development Bank Financial Leasing Co., Ltd.": "1606.HK",
    "Xinhu Zhongbao Co.,Ltd.": "600208.SS",
    "ShenZhen Woer Heat-Shrinkable Material Co.,Ltd.": "002130.SZ",
    "China State Construction Engineering Corporation Limited": "601668.SS",
    "Sino-Ocean Group Holding Limited": "3377.HK",
    "PT Bintang Oto Global Tbk": "BOGA.JK",
    "Katmerciler Arac Üstü Ekipman Sanayi ve Ticaret A.S.": "KATMR.IS",
    "PT Panin Financial Tbk": "PNLF.JK",
    "Ccoop Group Co., Ltd": "000564.SZ",
    "China United Network Communications Limited": "600050.SS",
    "KYE Systems Corp.": "2365.TW",
    "Tongling Nonferrous Metals Group Co.,Ltd.": "000630.SZ",
    "CRRC Corporation Limited": "601766.SS",
    "Çan2 Termik A.S.": "CANTE.IS",
    "Agricultural Bank of China Limited": "1288.HK",
    "Octopus Apollo VCT Ord": "OAP3.L",
    "PT J Resources Asia Pasifik Tbk": "PSAB.JK",
    "China National Nuclear Power Co., Ltd.": "601985.SS",
    "China XD Electric Co., Ltd": "601179.SS",
    "China Three Gorges Renewables (Group) Co.,Ltd.": "600905.SS",
    "Zijin Mining Group Company Limited": "601899.SS",
    "Emlak Konut Gayrimenkul Yatirim Ortakligi A.S.": "EKGYO.IS",
    "United Microelectronics Corporation": "2303.TW",
    "PT Kawasan Industri Jababeka Tbk": "KIJA.JK",
    "Yonghui Superstores Co., Ltd.": "601933.SS",
    "Kangmei Pharmaceutical Co., Ltd.": "600518.SS",
    "China Petroleum & Chemical Corporation": "600028.SS",
    "Plaza S.A.": "MALLPLAZA.SN",
    "PT Astra International Tbk": "ASII.JK",
    "Shin Kong Financial Holding Co., Ltd.": "2888.TW",
    "TCL Technology Group Corporation": "000100.SZ",
    "Datang International Power Generation Co., Ltd.": "601991.SS",
    "COSCO SHIPPING Holdings Co., Ltd.": "601919.SS",
    "PT Bukalapak.com Tbk.": "BUKA.JK",
    "PT Agung Podomoro Land Tbk": "APLN.JK",
    "Asia-Pacific Strategic Investments Limited": "5RA.SI",
    "Ping An Bank Co., Ltd.": "000001.SZ",
    "GD Power Development Co.,Ltd": "600795.SS",
    "Perusahaan Perseroan (Persero) PT Telekomunikasi Indonesia Tbk": "TLKM.JK",
    "China Petroleum & Chemical Corporation": "0386.HK",
    "PT Gozco Plantations Tbk": "GZCO.JK",
    "China Construction Bank Corporation": "601939.SS",
    "Yes Bank Limited": "YESBANK.NS",
    "China Everbright Bank Company Limited": "601818.SS",
    "China Telecom Corporation Limited": "0728.HK",
    "PT Wijaya Karya (Persero) Tbk": "WIKA.JK",
    "Fingerprint Cards AB (publ)": "FING-B.ST",
    "Postal Savings Bank of China Co., Ltd.": "601658.SS",
    "Langold Real Estate Co., Ltd.": "002305.SZ",
    "Goertek Inc.": "002241.SZ",
    "Zorlu Enerji Elektrik Üretim A.S.": "ZOREN.IS",
    "CMOC Group Limited": "603993.SS",
    "Beijing-Shanghai High-Speed Railway Co., Ltd.": "601816.SS",
    "PT Maharaksa Biru Energi Tbk": "OASA.JK",
    "PT PP (Persero) Tbk": "PTPP.JK",
    "Aluminum Corporation of China Limited": "601600.SS",
    "UK Oil & Gas PLC": "UKOG.L",
    "Tsinghua Tongfang Co., Ltd.": "600100.SS",
    "Sichuan Mingxing Electric Power Co., Ltd.": "600101.SS",
    "Sekerbank T.A.S.": "SKBNK.IS",
    "GS Chain plc": "GSC.L",
    "LAND Co., Ltd.": "8918.T",
    "Zhejiang Wanfeng Auto Wheel Co., Ltd.": "002085.SZ",
    "The Pacific Securities Co., Ltd": "601099.SS",
    "GCL Technology Holdings Limited": "3800.HK",
    "Premier African Minerals Limited": "PREM.L",
    "Bank of Communications Co., Ltd.": "601328.SS",
    "TMBThanachart Bank Public Company Limited": "TTB.BK",
    "Xingmin Intelligent Transportation Systems (Group) Co., Ltd.": "002355.SZ",
    "China Merchants Shekou Industrial Zone Holdings Co., Ltd.": "001979.SZ",
    "LingNan Eco&Culture-Tourism Co.,Ltd.": "002717.SZ",
    "PT Sarana Mitra Luas Tbk": "SMIL.JK",
    "PT Bekasi Fajar Industrial Estate Tbk": "BEST.JK",
    "Foxconn Industrial Internet Co., Ltd.": "601138.SS",
    "PT Bank Mandiri (Persero) Tbk": "BMRI.JK",
    "Shenzhen Microgate Technology Co., Ltd.": "300319.SZ",
    "Shenzhen Ecobeauty Co., Ltd.": "000010.SZ",
    "PT Bank Victoria International Tbk": "BVIC.JK",
    "PT Merdeka Battery Materials Tbk.": "MBMA.JK",
    "Tianfeng Securities Co., Ltd.": "601162.SS",
    "VGI Public Company Limited": "VGI.BK",
    "Ihlas Holding A.S.": "IHLAS.IS",
    "Anhui Jianghuai Automobile Group Corp.,Ltd.": "600418.SS",
    "Bank of Jiangsu Co., Ltd.": "600919.SS",
    "Greenland Holdings Corporation Limited": "600606.SS",
    "Chongqing Changan Automobile Company Limited": "000625.SZ",
    "Huadian Power International Corporation Limited": "600027.SS",
    "HUMBL, Inc.": "HMBL",
    "Weichai Power Co., Ltd.": "000338.SZ",
    "Huawen Media Group": "000793.SZ",
    "Innovation New Material Technology Co., Ltd.": "600361.SS",
    "Xiaomi Corporation": "1810.HK",
    "PT Astrindo Nusantara Infrastruktur Tbk": "BIPI.JK",
    "PT Adhi Karya (Persero) Tbk": "ADHI.JK",
    "China Minsheng Banking Corp., Ltd.": "600016.SS",
    "China Unicom (Hong Kong) Limited": "0762.HK",
    "PT Berdikari Pondasi Perkasa Tbk": "BDKR.JK",
    "CNOOC Limited": "0883.HK",
    "Complete Solaria, Inc.": "CSLR",
    "Zhejiang Garden Biopharmaceutical Co.,Ltd.": "300401.SZ",
    "EVA Airways Corp.": "2618.TW",
    "PT Solusi Sinergi Digital Tbk": "WIFI.JK",
    "CIFI Holdings (Group) Co. Ltd.": "0884.HK",
    "Shenzhen Deren Electronic Co., Ltd.": "002055.SZ",
    "GTL Infrastructure Limited": "GTLINFRA.NS",
    "Samart Digital Public Company Limited": "SDC.BK",
    "China Zheshang Bank Co., Ltd": "601916.SS",
    "Daqin Railway Co., Ltd.": "601006.SS",
    "NVIDIA Corporation": "NVDA",
    "Leo Group Co., Ltd.": "002131.SZ",
    "Sonaecom, SGPS, S.A.": "0IZ2.L",
    "Shanghai Metersbonwe Fashion and Accessories Co., Ltd.": "002269.SZ",
    "Dalian Thermal Power Co.,Ltd.": "600719.SS",
    "China Shipbuilding Industry Company Limited": "601989.SS",
    "PT Bumi Resources Tbk": "BUMI.JK",
    "Shandong Nanshan Aluminium Co.,Ltd.": "600219.SS",
    "Shandong Xinchao Energy Corporation Limited": "600777.SS",
    "Safe Orthopaedics SA": "ALSAF.PA",
    "Zhuguang Holdings Group Company Limited": "1176.HK",
    "Jilin Electric Power Co.,Ltd.": "000875.SZ",
    "Bosideng International Holdings Limited": "3998.HK",
    "Bomin Electronics Co., Ltd.": "603936.SS",
    "Vodafone Idea Limited": "IDEA.BO",
    "Tibet Tianlu Co., Ltd.": "600326.SS",
    "OFILM Group Co., Ltd.": "002456.SZ",
    "TV18 Broadcast Limited": "TV18BRDCST.NS",
    "Indian Overseas Bank": "IOB.NS",
    "Patel Engineering Limited": "PATELENG.NS",
    "ICICI Bank Limited": "ICICIBANK.NS",
    "Coal India Limited": "COALINDIA.NS",
    "SJVN Limited": "SJVN.NS",
    "Filatex Fashions Limited": "FILATFASH.NS",
    "Valor Estate Limited": "DBREALTY.NS",
    "Subex Limited": "SUBEXLTD.NS",
    "Central Depository Services (India) Limited": "CDSL.NS",
    "Indo Count Industries Limited": "ICIL.NS",
    "Morepen Laboratories Limited": "MOREPENLAB.NS",
    "The Tata Power Company Limited": "TATAPOWER.NS",
    "Central Bank of India": "CENTRALBK.NS",
    "RailTel Corporation of India Limited": "RAILTEL.NS",
    "Inventure Growth & Securities Limited": "INVENTURE.NS",
    "Burnpur Cement Limited": "BURNPUR.NS",
    "ALOK INDUSTRIES LTD.": "ALOKINDS.BO",
    "Refex Industries Limited": "REFEX.NS",
    "Shrenik Limited": "SHRENIK.NS",
    "Steel Exchange India Limited": "STEELXIND.NS",
    "NCL Research & Financial Services Limited": "NCLRESE.BO",
    "Reliance Infrastructure Limited": "RELINFRA.NS",
    "Bandhan Bank Limited": "BANDHANBNK.NS",
    "Motherson Sumi Wiring India Limited": "MSUMI.NS",
    "MFL India Limited": "MFLINDIA.BO",
    "Ambuja Cements Limited": "AMBUJACEM.NS",
    "Infosys Limited": "INFY.NS",
    "Birlasoft Limited": "BSOFT.NS",
    "Dhani Services Limited": "DHANI.NS",
    "Indraprastha Gas Limited": "IGL.NS",
    "Unitech Limited": "UNITECH.NS",
    "Ion Exchange (India) Limited": "IONEXCHANG.NS",
    "Indian Renewable Energy Development Agency Limited": "IREDA.BO",
    "Black Box Limited": "BBOX.NS",
    "Allcargo Logistics Limited": "ALLCARGO.NS",
    "Bharti Airtel Limited": "BHARTIARTL.NS",
    "KBC Global Limited": "KBCGLOBAL.NS",
    "The Bombay Dyeing and Manufacturing Company Limited": "BOMDYEING.NS",
    "PMC Fincorp Limited": "PMCFIN.BO",
    "JK Tyre & Industries Limited": "JKTYRE.NS",
    "FCS Software Solutions Limited": "FCSSOFT.BO",
    "Zee Media Corporation Limited": "ZEEMEDIA.NS",
    "Wockhardt Limited": "WOCKPHARMA.NS",
    "Stanley Lifestyles Ltd": "STANLEY.NS",
    "Udaipur Cement Works Limited": "UDAICEMENT.NS",
    "Axis Bank Limited": "AXISBANK.NS",
    "RattanIndia Power Limited": "RTNPOWER.BO",
    "Kanani Industries Limited": "KANANIIND.NS",
    "Bank of India Limited": "BANKINDIA.NS",
    "Indiabulls Housing Finance Limited": "IBULHSGFIN.NS",
    "Edelweiss Financial Services Limited": "EDELWEISS.NS",
    "Hindustan Copper Limited": "HINDCOPPER.NS",
    "Inox Wind Limited": "INOXWIND.NS",
    "Ircon International Limited": "IRCON.NS",
    "Gujarat State Fertilizers & Chemicals Limited": "GSFC.NS",
    "Lloyds Engineering Works Limited": "LLOYDSENGG.NS",
    "Visagar Polytex Limited": "VIVIDHA.NS",
    "The Federal Bank Limited": "FEDERALBNK.NS",
    "Atul Auto Limited": "ATULAUTO.NS",
    "One Point One Solutions Limited": "ONEPOINT.NS",
    "NMDC Steel Limited": "NSLNISP.NS",
    "RattanIndia Enterprises Limited": "RTNINDIA.NS",
    "Hathway Cable and Datacom Limited": "HATHWAY.NS",
    "Easy Trip Planners Limited": "EASEMYTRIP.NS",
    "ARC Finance Limited": "ARCFIN.BO",
    "Mazagon Dock Shipbuilders Limited": "MAZDOCK.NS",
    "Vakrangee Limited": "VAKRANGEE.NS",
    "Chambal Fertilisers and Chemicals Limited": "CHAMBLFERT.NS",
}