# company_symbols.py

company_to_symbol = {
    "APPLE": "AAPL",
    "MICROSOFT": "MSFT",
    "GOOGLE": "GOOGL",
    "AMAZON": "AMZN",
    "TESLA": "TSLA",
    "FACEBOOK": "META",
    "BERKSHIRE HATHAWAY": "BRK-A",
    "JOHNSON & JOHNSON": "JNJ",
    "VISA": "V",
    "WALMART": "WMT",
    "JPMORGAN CHASE": "JPM",
    "MASTERCARD": "MA",
    "PROCTER & GAMBLE": "PG",
    "UNITEDHEALTH": "UNH",
    "NVIDIA": "NVDA",
    "HOME DEPOT": "HD",
    "PAYPAL": "PYPL",
    "WALT DISNEY": "DIS",
    "NETFLIX": "NFLX",
    "ADOBE": "ADBE",
    "PEPSICO": "PEP",
    "COCA-COLA": "KO",
    "INTEL": "INTC",
    "VERIZON": "VZ",
    "AT&T": "T",
    "CISCO": "CSCO",
    "SALESFORCE": "CRM",
    "NIKE": "NKE",
    "EXXON MOBIL": "XOM",
    "CHEVRON": "CVX",
    "PHILIP MORRIS": "PM",
    "PFIZER": "PFE",
    "ABBVIE": "ABBV",
    "MERCK": "MRK",
    "BROADCOM": "AVGO",
    "QUALCOMM": "QCOM",
    "IBM": "IBM",
    "ORACLE": "ORCL",
    "SAP": "SAP",
    "ZOOM": "ZM",
    "SHOPIFY": "SHOP",
    "TWITTER": "TWTR",
    "UBER": "UBER",
    "LYFT": "LYFT",
    "SQUARE": "SQ",
    "SNAPCHAT": "SNAP",
    "DROPBOX": "DBX",
    "SPOTIFY": "SPOT",
    "ROBINHOOD": "HOOD",
    "REDDIT": "REDDIT",
    "SNOWFLAKE": "SNOW",
    "AIRBNB": "ABNB",
    "DOORDASH": "DASH",
    "ZOOM": "ZM",
    "DOCUSIGN": "DOCU",
    "TESLA": "TSLA",
    "RIVIAN": "RIVN",
    "NIO": "NIO",
    "XPENG": "XPEV",
    "FORD": "F",
    "GENERAL MOTORS": "GM",
    "TOYOTA": "TM",
    "HONDA": "HMC",
    "NISSAN": "NSANY",
    "VOLKSWAGEN": "VWAGY",
    "BMW": "BMWYY",
    "DAIMLER": "DDAIF",
    "MERCEDES-BENZ": "DDAIF",
    "AUDI": "AUDVF",
    "FERRARI": "RACE",
    "LAMBORGHINI": "VLKAY",
    "BUGATTI": "PCARF",
    "MASERATI": "STLA",
    "BENTLEY": "VLKAY",
    "ROLLS-ROYCE": "RR",
    "ASTON MARTIN": "AML",
    "PORSCHE": "POAHY",
    "JAGUAR": "TTM",
    "LAND ROVER": "TTM",
    "SUBARU": "FUJHY",
    "MAZDA": "MZDAY",
    "MITSUBISHI": "MSBHY",
    "ISUZU": "ISUZY",
    "KIA": "KIMTF",
    "HYUNDAI": "HYMTF",
    "SAMSUNG": "SSNLF",
    "LG": "LPL",
    "SONY": "SONY",
    "PANASONIC": "PCRFY",
    "SHARP": "SHCAY",
    "PHILIPS": "PHG",
    "TOSHIBA": "TOSBF",
    "HITACHI": "HTHIY",
    "FUJIFILM": "FUJIY",
    "NIKON": "NINOY",
    "CANON": "CAJ",
    "OLYMPUS": "OCPNY",
    "PIONEER": "PNCOF",
    "ONKYO": "ONKYO",
    "JVC": "JVC",
    "KENWOOD": "KENWOOD",
    "PIONEER": "PNCOF",
    "YAMAHA": "YAMCY",
    "DENON": "DENON",
    "BOSE": "BOSE",
    "BANG & OLUFSEN": "BO",
    "SENNHEISER": "SENNHEISER",
    "PHILIPS": "PHG",
    "BOSCH": "ROBFY",
    "SIEMENS": "SIEGY",
    "GE": "GE",
    "HONEYWELL": "HON",
    "3M": "MMM",
    "ABB": "ABB",
    "SCHNEIDER ELECTRIC": "SBGSF",
    "EMERSON": "EMR",
    "ROCKWELL AUTOMATION": "ROK",
    "KEYENCE": "KEYCY",
    "YASKAWA": "YASKY",
    "MITSUBISHI ELECTRIC": "MIELY",
    "FUJI ELECTRIC": "FELTY",
    "HITACHI": "HTHIY",
    "TOSHIBA": "TOSBF",
    "PANASONIC": "PCRFY",
    "SONY": "SONY",
    "SAMSUNG": "SSNLF",
    "LG": "LPL",
    "VESTAS": "VWDRY",
    "SIEMENS GAMESA": "GCTAY",
    "GE RENEWABLE ENERGY": "GE",
    "NEXTERA ENERGY": "NEE",
    "DUKE ENERGY": "DUK",
    "DOMINION ENERGY": "D",
    "AMERICAN ELECTRIC POWER": "AEP",
    "SOUTHERN COMPANY": "SO",
    "EXELON": "EXC",
    "FIRSTENERGY": "FE",
    "PG&E": "PCG",
    "PPL": "PPL",
    "SCE&G": "SCEG",
    "NV ENERGY": "NVE",
    "TECO ENERGY": "TE",
    "CONSOLIDATED EDISON": "ED",
    "ENTERGY": "ETR",
    "EVERGY": "EVRG",
    "HAWAIIAN ELECTRIC": "HE",
    "IDACORP": "IDA",
    "ALLIANT ENERGY": "LNT",
    "XCEL ENERGY": "XEL",
    "PUBLIC SERVICE ENTERPRISE GROUP": "PEG",
    "FORTIS": "FTS",
    "HYDRO ONE": "H",
    "EMERA": "EMA",
    "ALTAGAS": "ALA",
    "TRANSCANADA": "TRP",
    "ENBRIDGE": "ENB",
    "PEMBINA": "PBA",
    "INTER PIPELINE": "IPL",
    "KEYERA": "KEY",
    "VERMILION ENERGY": "VET",
    "CRESCENT POINT ENERGY": "CPG",
    "WHITECAP RESOURCES": "WCP",
    "TORC OIL & GAS": "TOG",
    "OBSIDIAN ENERGY": "OBE",
    "PRAIRIESKY ROYALTY": "PSK",
    "FREEHOLD ROYALTIES": "FRU",
    "RAGING RIVER EXPLORATION": "RRX",
    "SPARTAN ENERGY": "SPE",
    "BAYTEX ENERGY": "BTE",
    "MEG ENERGY": "MEG",
    "SEVEN GENERATIONS ENERGY": "VII",
    "PENGROWTH ENERGY": "PGF",
    "PENN WEST PETROLEUM": "PWE",
    "ATHABASCA OIL": "ATH",
    "JUPITER RESOURCES": "JUPR",
    "NUVISTA ENERGY": "NVA",
    "CENOVUS ENERGY": "CVE",
    "CANADIAN NATURAL RESOURCES": "CNQ",
    "SUNCOR ENERGY": "SU",
    "HUSKY ENERGY": "HSE",
    "IMPERIAL OIL": "IMO",
    "NEXEN ENERGY": "NXY",
    "TALISMAN ENERGY": "TLM",
    "DEVON ENERGY": "DVN",
    "MURPHY OIL": "MUR",
    "APACHE CORPORATION": "APA",
    "MARATHON OIL": "MRO",
    "CONOCOPHILLIPS": "COP",
    "CHEVRON": "CVX",
    "EXXONMOBIL": "XOM",
    "BP": "BP",
    "ROYAL DUTCH SHELL": "RDS-A",
    "TOTAL": "TOT",
    "EQUINOR": "EQNR",
    "ENI": "E",
    "OMV": "OMVKY",
    "REPSOL": "REPYY",
    "GAZPROM": "OGZPY",
    "LUKOIL": "LUKOY",
    "ROSNEFT": "OJSCY",
    "PETROBRAS": "PBR",
    "CNOOC": "CEO",
    "PETROCHINA": "PTR",
    "SINOPEC": "SNP",
    "PETRONAS": "PETR",
    "CNPC": "CNPC",
    "KAZMUNAIGAS": "KMG",
    "SAUDI ARAMCO": "ARAMCO",
    "QATAR PETROLEUM": "QATPE",
    "ADNOC": "ADNOC",
    "KUWAIT OIL": "KOC",
    "BAHRAIN PETROLEUM": "BAPCO",
    "Kingkey Financial International (Holdings) Limited": "1468.HK",
    "Supply@ME Capital plc": "SYME.L",
    "Echo Energy plc": "ECHO.L",
    "Vodafone Idea Limited": "IDEA.NS",
    "United Energy Group Limited": "0467.HK",
    "LATAM Airlines Group S.A.": "LTM.SN",
    "China Grand Automotive Services Group Co.,Ltd": "600297.SS",
    "BAIC BluePark New Energy Technology Co.,Ltd.": "600733.SS",
    "Lingyi iTech (Guangdong) Company": "002600.SZ",
    "Hainan Airlines Holding Co., Ltd.": "600221.SS",
    "PT Barito Pacific Tbk": "BRPT.JK",
    "China Construction Bank Corporation": "0939.HK",
    "Bluejay Mining plc": "JAY.L",
    "PT GoTo Gojek Tokopedia Tbk": "GOTO.JK",
    "Topindo Solusi Komunika Tbk.": "TOSK.JK",
    "SAS AB (publ)": "SAS.ST",
    "Mosman Oil and Gas Limited": "MSMN.L",
    "Energy Absolute Public Company Limited": "EA.BK",
    "Energy Absolute Public Company Limited": "EA-R.BK",
    "SenseTime Group Inc.": "0020.HK",
    "Industrial and Commercial Bank of China Limited": "1398.HK",
    "PT Buana Lintas Lautan Tbk": "BULL.JK",
    "PT Totalindo Eka Persada Tbk": "TOPS.JK",
    "Guangdong Highsun Group Co.,Ltd.": "000861.SZ",
    "Agricultural Bank of China Limited": "601288.SS",
    "Inner Mongolia Baotou Steel Union Co., Ltd.": "600010.SS",
    "Meyer Burger Technology AG": "MBTN.SW",
    "China Vered Financial Holding Corporation Limited": "0245.HK",
    "PT Era Media Sejahtera Tbk": "DOOH.JK",
    "Industrial and Commercial Bank of China Limited": "601398.SS",
    "Sabuy Technology Public Company Limited": "SABUY.BK",
    "Sabuy Technology Public Company Limited": "SABUY-R.BK",
    "CAP-XX Limited": "CPX.L",
    "China Tower Corporation Limited": "0788.HK",
    "Helium One Global Ltd": "HE1.L",
    "Nippon Telegraph and Telephone Corporation": "9432.T",
    "Cybergun S.A.": "ALCYB.PA",
    "China Vanke Co., Ltd.": "000002.SZ",
    "Orient Group Incorporation": "600811.SS",
    "PT Bank Rakyat Indonesia (Persero) Tbk": "BBRI.JK",
    "PT Samudera Indonesia Tbk": "SMDR.JK",
    "Jinke Property Group Co., Ltd.": "000656.SZ",
    "East Money Information Co.,Ltd.": "300059.SZ",
    "Clontarf Energy plc": "CLON.L",
    "Gfinity plc": "GFIN.L",
    "Gemdale Corporation": "600383.SS",
    "Bank of China Limited": "3988.HK",
    "Beijing Hualian Department Store Co., Ltd": "000882.SZ",
    "Wintime Energy Group Co.,Ltd.": "600157.SS",
    "BOE Technology Group Company Limited": "000725.SZ",
    "5i5j Holding Group Co., Ltd.": "000560.SZ",
    "Chengtun Mining Group Co., Ltd.": "600711.SS",
    "Offcn Education Technology Co., Ltd.": "002607.SZ",
    "Gosuncn Technology Group Co., Ltd.": "300098.SZ",
    "Türkiye Is Bankasi A.S.": "ISCTR.IS",
    "Founder Technology Group Co.,Ltd.": "600601.SS",
    "PT Lippo Karawaci Tbk": "LPKR.JK",
    "PT Darma Henwa Tbk": "DEWA.JK",
    "Poly Developments and Holdings Group Co., Ltd.": "600048.SS",
    "RiseSun Real Estate Development Co.,Ltd": "002146.SZ",
    "Power Construction Corporation of China, Ltd": "601669.SS",
    "CGN Power Co., Ltd.": "003816.SZ",
    "Bank of China Limited": "601988.SS",
    "Nex Point Public Company Limited": "NEX.BK",
    "Nex Point Public Company Limited": "NEX-R.BK",
    "China Energy Engineering Corporation Limited": "601868.SS",
    "PetroChina Company Limited": "0857.HK",
    "Atlantis Subsea Indonesia Tbk.": "ATLA.JK",
    "PetroChina Company Limited": "601857.SS",
    "Trabzonspor Sportif Yatirim ve Futbol Isletmeciligi Ticaret A.S.": "TSPOR.IS",
    "China Development Bank Financial Leasing Co., Ltd.": "1606.HK",
    "Xinhu Zhongbao Co.,Ltd.": "600208.SS",
    "ShenZhen Woer Heat-Shrinkable Material Co.,Ltd.": "002130.SZ",
    "China State Construction Engineering Corporation Limited": "601668.SS",
    "Sino-Ocean Group Holding Limited": "3377.HK",
    "PT Bintang Oto Global Tbk": "BOGA.JK",
    "Katmerciler Arac Üstü Ekipman Sanayi ve Ticaret A.S.": "KATMR.IS",
    "PT Panin Financial Tbk": "PNLF.JK",
    "Ccoop Group Co., Ltd": "000564.SZ",
    "China United Network Communications Limited": "600050.SS",
    "KYE Systems Corp.": "2365.TW",
    "Tongling Nonferrous Metals Group Co.,Ltd.": "000630.SZ",
    "CRRC Corporation Limited": "601766.SS",
    "Çan2 Termik A.S.": "CANTE.IS",
    "Agricultural Bank of China Limited": "1288.HK",
    "Octopus Apollo VCT Ord": "OAP3.L",
    "PT J Resources Asia Pasifik Tbk": "PSAB.JK",
    "China National Nuclear Power Co., Ltd.": "601985.SS",
    "China XD Electric Co., Ltd": "601179.SS",
    "China Three Gorges Renewables (Group) Co.,Ltd.": "600905.SS",
    "Zijin Mining Group Company Limited": "601899.SS",
    "Emlak Konut Gayrimenkul Yatirim Ortakligi A.S.": "EKGYO.IS",
    "United Microelectronics Corporation": "2303.TW",
    "PT Kawasan Industri Jababeka Tbk": "KIJA.JK",
    "Yonghui Superstores Co., Ltd.": "601933.SS",
    "Kangmei Pharmaceutical Co., Ltd.": "600518.SS",
    "China Petroleum & Chemical Corporation": "600028.SS",
    "Plaza S.A.": "MALLPLAZA.SN",
    "PT Astra International Tbk": "ASII.JK",
    "Shin Kong Financial Holding Co., Ltd.": "2888.TW",
}